# Site settings
title: "Pé de Moleque"
description: "Um Podcast de cultura e política de Piranguinho, MG"
podcast-description: "Um Podcast de cultura e política de Piranguinho, MG"
url:  "https//pedemoleque.github.io/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Beta Brandão"
  email: "beta@robertabrandao.com.br"
  url: "https://www.robertabrandao.com.br"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: alinefree
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Pé de Moleque
  links:
    - https://github.com/daroca-eco-br/
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Pé de Moleque Poscast
podcast_author: Beta Brandão
podcast_email: beta@brobertabrandao.com.br
podcast_subtitle: "Piranguinho, sul de MG"
podcast_summary: "Um Podcast de cultura e política de Piranguinho, MG"
podcast_description: "Um Podcast de cultura e política de Piranguinho, MG"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2022-11-10" #Launch date of your podcast
podcast_copyright: "&#xA9;Beta Brandão"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
